create database zyvana;
use zyvana;
select * from details; 
describe details;
select * from orders;
describe orders;
-------------------------------------------------------------------------
#RENAING THE COLUMN ORDER DATE
ALTER TABLE orders
RENAME COLUMN `Order Date` TO Order_Date;
----------------------------------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
UPDATE orders
SET Order_Date = STR_TO_DATE(Order_Date, '%d-%m-%Y');
ALTER TABLE orders
MODIFY Order_Date DATE;
SET SQL_SAFE_UPDATES = 1;
-------------------------------------------------------------------------------
select * from orders;
describe orders;
------------------------------------------------------------------------------
# 1. Sales-to-profit mismatch
# Which sub-categories generate substantial sales but contribute disproportionately less profit?

# RENAMING THE SUB-CATEGORY COLUMN TO SUB_CATEGORY
alter table details 
rename column `Sub-Category` to sub_category;
describe details;

with sub_category_profitability as(
     select 
		sub_category, 
        sum(Amount) as total_sales,
        sum(Profit) as total_profit,
        sum(Profit)/sum(Amount)*100 as profit_margin
	 from details
     group by sub_category
)
select sub_category, total_sales, total_profit, round(profit_margin ,2) as rounded_profit_margin
from sub_category_profitability 
    where total_sales >= (select avg(total_sales) as avg_sales from sub_category_profitability)
         and profit_margin < (select avg(profit_margin) as avg_profit_margin from sub_category_profitability)
order by total_sales desc;

# Strong sales do not always mean strong profitability.
-----------------------------------------------------------------------------
# 2. Profitability opportunity segments
# Which sub-categories have both meaningful sales contribution and below-average profit margins, making them potential areas for profitability improvement?

with sub_category_profitability as(
     select 
		sub_category, 
        sum(Amount) as total_sales,
        sum(Profit) as total_profit,
        sum(Profit)/sum(Amount)*100 as profit_margin
	 from details
     group by sub_category
)
select sub_category, total_sales, total_profit, round(profit_margin ,2) as rounded_profit_margin
from sub_category_profitability 
    where total_sales >= (select avg(total_sales) as avg_sales from sub_category_profitability)
         and profit_margin <= (select avg(profit_margin) as avg_profit_margin from sub_category_profitability)
order by total_sales desc;

# Focus on high-sales segments where margin improvement can create a meaningful impact on overall profitability.
-------------------------------------------------------------------------------
select * from details;
select * from orders;
alter table details 
rename column `Order ID` to Order_ID;
alter table orders
rename column `Order ID` to Order_ID;
-----------------------------------------------------------------------------
# 3. Customer profitability
# Which customers generate high sales but relatively low profit?

with high_sales as(
     select o.CustomerName,
            sum(d.Amount) as total_sales,
            sum(d.Profit) as total_profit
            from orders o
            join details d on o.Order_ID=d.Order_ID
            group by o.CustomerName
)
select CustomerName, total_sales, total_profit from high_sales
where total_sales >= (select avg(total_sales) from high_sales) and total_profit < (select avg(total_profit) from high_sales)
order by total_sales desc;

# These customers represent potential profitability-risk segments because their sales contribution is not translating into positive profit.

------------------------------------------------------------------------------------------------------

# 4. High-value customer contribution
# What percentage of total sales and profit is generated by the top 10% of customers?

with percentage as (
     select 
        o.CustomerName,
        sum(d.Amount) as total_sales,
        sum(d.Profit) as total_profit
        from orders o 
        join details d on o.Order_ID=d.Order_ID
        group by o.CustomerName
),
ranked_customers as (
      select CustomerName, total_sales, total_profit,
      row_number() over(order by total_sales desc) as customer_rank,
      count(*) over() as total_customers
      from percentage
)
select round(sum(total_sales)/(select sum(total_sales) from percentage)*100,2) as sales_percentage,
round(sum(total_profit)/(select sum(total_profit) from percentage)*100,2) as profit_percentage
from ranked_customers
where customer_rank <=ceil(total_customers*0.10);
-------------------------------------------------------------------------------------------------------------
# 5. Customer order economics
# Which customers place multiple orders but generate relatively low profit per order?

with customer_orders as(
	  select o.CustomerName,
			 o.Order_ID,
             sum(d.Profit) as total_profit
             from orders o join details d on o.Order_ID=d.Order_ID
             group by o.CustomerName, o.Order_ID
),

customer_economics as(
       select CustomerName,
			  count(Order_ID) as total_orders,
              sum(total_profit) as order_total_profit,
              sum(total_profit)/count(Order_ID) as profit_per_order
			from customer_orders
            group by CustomerName
)

select CustomerName,
       total_orders,
       order_total_profit,
       round(profit_per_order,2) as profit_per_order
	from customer_economics
    where total_orders > 1
       and profit_per_order < (select avg(profit_per_order) from customer_economics)
       order by profit_per_order desc;
---------------------------------------------------------------------------------------------------------------------
select * from Orders;
# 6. Geographic profitability gap
# Which states generate significant sales but have below-average profit margins?

with states as (
     select o.State, 
            sum(d.Amount) as total_sales,
            sum(d.profit) as total_profit,
            sum(d.profit)/sum(d.Amount)*100 as profit_margin
            from Orders o join Details d on o.Order_ID=d.Order_ID
		group by o.State
)
select State, total_sales, total_profit, round(profit_margin,2) as profit_margin from states
where total_sales >= (select avg(total_sales) from states) and profit_margin < (select avg(profit_margin) from states)
order by total_sales desc;
------------------------------------------------------------------------------------------------------------------
# 7. City-level opportunity analysis
# Which cities combine meaningful order volume with weak profitability?

with citys as(
select o.City, 
       count(distinct o.Order_ID) as total_orders,
       sum(d.Profit) as total_profit,
       sum(d.Profit)/sum(d.Amount)*100 as profit_margin
	   from Orders o join Details d on o.Order_ID=d.Order_ID
       group by o.City
)
select City, total_orders, total_profit, round(profit_margin,2) as profit_margin
from citys where total_orders >=(select avg(total_orders) from citys) and total_profit < (select avg(total_profit) from citys)
order by total_orders desc;
--------------------------------------------------------------------------------------------------------------------
# 8. Profit concentration
# What percentage of total profit is generated by the top-performing sub-categories and customers?

with sub_category_profit as(
     select Sub_Category as segment,
     sum(Profit) as total_profit
     from details group by Sub_Category
),
customer_profit as(
    select o.CustomerName as segment,
    sum(d.Profit) as total_profit
    from Orders o join Details d on o.Order_ID=d.Order_ID
    group by o.CustomerName
)
select 'Sub_Category' as segment_type,
           ROUND(
        SUM(total_profit) /
        (SELECT SUM(total_profit) FROM sub_category_profit) * 100,
        2
    ) AS profit_percentage
FROM (
    SELECT
        segment,
        total_profit,
        ROW_NUMBER() OVER (ORDER BY total_profit DESC) AS profit_rank
    FROM sub_category_profit
) s
WHERE profit_rank <= 5

UNION ALL

SELECT
    'Customer' AS segment_type,
    ROUND(
        SUM(total_profit) /
        (SELECT SUM(total_profit) FROM customer_profit) * 100,
        2
    ) AS profit_percentage
FROM (
    SELECT
        segment,
        total_profit,
        ROW_NUMBER() OVER (ORDER BY total_profit DESC) AS profit_rank
    FROM customer_profit
) c
WHERE profit_rank <= 5;
-----------------------------------------------------------------------------------------------------
# 9. Category-level customer behavior
# Which customers contribute the most profit within each product category?

with customer_contribution as (
     select o.CustomerName,
            d.Category,
		    sum(d.Profit) as total_profit
            from Orders o join Details d on o.Order_ID=d.Order_ID
            group by d.Category, o.CustomerName
),
ranked_customers as(
	 select CustomerName,
            Category,
            total_profit,
            rank() over(partition by category order by total_profit desc) as profit_rank
            from customer_contribution
)
select category,
       CustomerName,
       total_profit
       from ranked_customers
       where profit_rank=1
       order by Category;
-----------------------------------------------------------------------------------------------
# 10. Payment behavior vs profitability
# Do different payment methods show meaningful differences in average order value or profit contribution?

with order_payment as(
     select o.Order_Id,
            d.PaymentMode,
            sum(d.Amount) as order_value,
            sum(d.Profit) as order_profit
            from Orders o join Details d on o.Order_ID=d.Order_ID
            group by o.Order_ID, d.PaymentMode
),
payment_analysis as(
       select PaymentMode,
              count(Order_ID) as total_orders,
              avg(Order_Value) as avg_order_value,
              sum(order_profit) as total_order_profit
              from order_payment
              group by PaymentMode
)
select PaymentMode,
       total_orders,
       round(avg_order_value,2) as avg_order_value,
       total_order_profit,
       round(
           total_order_profit/(select sum(total_order_profit) from payment_analysis)*100,2
		) as profit_contribution
from payment_analysis
order by total_order_profit desc;
---------------------------------------------------------------------------------------------
# 11. Low-profit high-volume segments
# Which segments have high quantities sold but comparatively low profit, indicating potential opportunities to improve the profitability of high-volume sales?

WITH subcategory_analysis AS (
    SELECT
        sub_category,
        SUM(Quantity) AS total_quantity,
        SUM(Amount) AS total_sales,
        SUM(Profit) AS total_profit,
        SUM(Profit) / SUM(Amount) * 100 AS profit_margin
    FROM Details
    GROUP BY sub_category
)
SELECT
    sub_category,
    total_quantity,
    total_sales,
    total_profit,
    ROUND(profit_margin, 2) AS profit_margin
FROM subcategory_analysis
WHERE total_quantity >= (
    SELECT AVG(total_quantity)
    FROM subcategory_analysis
)
AND total_profit < (
    SELECT AVG(total_profit)
    FROM subcategory_analysis
)
ORDER BY total_quantity DESC;
--------------------------------------------------------------------------------------------------
# 12. Profitability ranking
# Rank customers and sub-categories based on profit contribution to identify the strongest and weakest contributors.

WITH customer_profit AS (
    SELECT
        o.CustomerName AS segment,
        SUM(d.Profit) AS total_profit
    FROM Orders o
    JOIN Details d
        ON o.Order_ID = d.Order_ID
    GROUP BY o.CustomerName
),

subcategory_profit AS (
    SELECT
        sub_category AS segment,
        SUM(Profit) AS total_profit
    FROM Details
    GROUP BY sub_category
)

SELECT
    'Customer' AS segment_type,
    segment,
    total_profit,
    DENSE_RANK() OVER (ORDER BY total_profit DESC) AS profit_rank
FROM customer_profit

UNION ALL

SELECT
    'Sub-Category' AS segment_type,
    segment,
    total_profit,
    DENSE_RANK() OVER (ORDER BY total_profit DESC) AS profit_rank
FROM subcategory_profit
ORDER BY segment_type, profit_rank;


